In [116]:
import numpy as np
import pandas as pd

In [117]:
df=pd.read_csv("../data-visualization/master_order_table.csv")
df

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,actual_delivery_days,delivery_delay_days,late_delivery_flag,review_risk_flag
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,7c396fd4830fd04220f754e42b4e5bff,3149,...,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,8.0,-8.0,False,False
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,af07308b275d755c9edb36a90c618231,47813,...,8d5266042046a06655c8db133d120ba5,4.0,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,13.0,-6.0,False,False
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,e73b67b67587f7644d5bd1a52deb1b01,5.0,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,9.0,-18.0,False,False
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,7c142cf63193a1473d2e66489a9ae977,59296,...,359d03e676b3c069f62cadba8dd3f6e8,5.0,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58,13.0,-13.0,False,False
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,e50934924e227544ba8246aeb3770dd4,5.0,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51,2.0,-10.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28,6359f309b166b0196dbf7ad2ac62bb5a,12209,...,e262b3f92d1ce917aa412a9406cf61a6,5.0,NaN,NaN,2017-03-22 00:00:00,2017-03-23 11:02:08,8.0,-11.0,False,False
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02,da62f9e57a76d978d02ab5362c509660,11722,...,29bb71b2760d0f876dfa178a76bc4734,4.0,NaN,So uma peça que veio rachado mas tudo bem rs,2018-03-01 00:00:00,2018-03-02 17:50:01,22.0,-2.0,False,False
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27,737520a9aad80b3fbbdad19b66b37b30,45920,...,371579771219f6db2d830d50805977bb,5.0,NaN,Foi entregue antes do prazo.,2017-09-22 00:00:00,2017-09-22 23:10:57,24.0,-6.0,False,False
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15,5097a5312c8b157bb7be58ae360ef43c,28685,...,8ab6855b9fe9b812cd03a480a25058a1,2.0,NaN,Foi entregue somente 1. Quero saber do outro p...,2018-01-26 00:00:00,2018-01-27 09:16:56,17.0,-21.0,False,True
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03,60350aa974b26ff12caad89e55993bd6,83750,...,dc9c59b4688062c25758c2be4cafc523,5.0,NaN,NaN,2018-03-17 00:00:00,2018-03-17 16:33:31,7.0,-18.0,False,False

In [118]:
df.shape

(99441, 30)

In [119]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
 8   customer_unique_id             99441 non-null  str
 9   customer_zip_code_prefix       99441 non-null  int64
 10  customer_city                  99441 non-null  str
 11  customer_state                 99441 non-null  str
 12  order_item_count               98666 non-null  float64
 13  unique_sellers                 98666 non-null  float64
 14  unique_products                98666 non-null  float64
 15  total_freight_value            98666 non-null  float64
 16  total_item_value               98666 non-null  float64
 17  payment_value_total            99440 non-null  float64
 18  payment_installments_total     99440 non-null  float64
 19  payment_type_count             99440 non-null  float64
 20  review_id                      98673 non-null  str
 21  review_score                   98673 non-null  float64
 22  review_comment_title           11552 non-null  str
 23  review_comment_message         40776 non-null  str
 24  review_creation_date           98673 non-null  str
 25  review_answer_timestamp        98673 non-null  str
 26  actual_delivery_days           96476 non-null  float64
 27  delivery_delay_days            96476 non-null  float64
 28  late_delivery_flag             99441 non-null  bool
 29  review_risk_flag               99441 non-null  bool
dtypes: bool(2), float64(11), int64(1), str(16)
memory usage: 21.4 MB

In [120]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,99441,99441,e481f51cbdc54678b7cc49136f2d6af7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,99441,99441,9ef432eb6251297304e76186b10a928d,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_status,99441,8,delivered,96478,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_purchase_timestamp,99441,98875,2018-03-31 15:08:21,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_approved_at,99281,90733,2018-02-27 04:31:10,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_delivered_customer_date,96476,95664,2018-05-14 20:02:44,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_estimated_delivery_date,99441,459,2017-12-20,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,99441,96096,8d50f5eadf50201ccdcedfb9e2ac8455,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,99441.0,NaN,NaN,NaN,35137.474583,29797.938996,1003.0,11347.0,24416.0,58900.0,99990.0
customer_city,99441,4119,sao paulo,15540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,99441,27,SP,41746,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_count,98666.0,NaN,NaN,NaN,1.141731,0.538452,1.0,1.0,1.0,1.0,21.0
unique_sellers,98666.0,NaN,NaN,NaN,1.013622,0.122297,1.0,1.0,1.0,1.0,5.0
unique_products,98666.0,NaN,NaN,NaN,1.038098,0.226456,1.0,1.0,1.0,1.0,8.0
total_freight_value,98666.0,NaN,NaN,NaN,22.823562,21.650909,0.0,13.85,17.17,24.04,1794.96
total_item_value,98666.0,NaN,NaN,NaN,137.754076,210.645145,0.85,45.9,86.9,149.9,13440.0
payment_value_total,99440.0,NaN,NaN,NaN,160.990267,221.951257,0.0,62.01,105.29,176.97,13664.08
payment_installments_total,99440.0,NaN,NaN,NaN,2.980923,2.74181,0.0,1.0,2.0,4.0,29.0
payment_type_count,99440.0,NaN,NaN,NaN,1.022586,0.148582,1.0,1.0,1.0,1.0,2.0
review_id,98673,98114,08528f70f579f0c830189efc523d2182,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,98673.0,NaN,NaN,NaN,4.086265,1.347656,1.0,4.0,5.0,5.0,5.0
review_comment_title,11552,4525,Recomendo,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_message,40776,36064,Muito bom,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,98673,636,2017-12-19 00:00:00,459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_answer_timestamp,98673,97953,2017-06-15 23:21:05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
actual_delivery_days,96476.0,NaN,NaN,NaN,12.094086,9.551746,0.0,6.0,10.0,15.0,209.0
delivery_delay_days,96476.0,NaN,NaN,NaN,-11.876881,10.183854,-147.0,-17.0,-12.0,-7.0,188.0
late_delivery_flag,99441,2,False,92906,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_risk_flag,99441,2,False,84946,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [121]:
df.nunique().sort_values()

review_risk_flag                     2
late_delivery_flag                   2
payment_type_count                   2
unique_sellers                       5
review_score                         5
order_status                         8
unique_products                      8
order_item_count                    17
customer_state                      27
payment_installments_total          28
actual_delivery_days               146
delivery_delay_days                198
order_estimated_delivery_date      459
review_creation_date               636
customer_city                     4119
review_comment_title              4525
total_item_value                  7621
total_freight_value               7698
customer_zip_code_prefix         14994
payment_value_total              27713
review_comment_message           36064
order_delivered_carrier_date     81018
order_approved_at                90733
order_delivered_customer_date    95664
customer_unique_id               96096
review_answer_timestamp          97953
review_id                        98114
order_purchase_timestamp         98875
order_id                         99441
customer_id                      99441
dtype: int64

In [122]:
missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

missing_pct = (
    df.isna()
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

missing_summary = pd.DataFrame({
    "missing_count": missing,
    "missing_pct": missing_pct
})

missing_summary

                               missing_count  missing_pct
review_comment_title                   87889    88.383061
review_comment_message                 58665    58.994781
delivery_delay_days                     2965     2.981668
actual_delivery_days                    2965     2.981668
order_delivered_customer_date           2965     2.981668
order_delivered_carrier_date            1783     1.793023
unique_sellers                           775     0.779357
total_item_value                         775     0.779357
total_freight_value                      775     0.779357
unique_products                          775     0.779357
order_item_count                         775     0.779357
review_score                             768     0.772317
review_creation_date                     768     0.772317
review_answer_timestamp                  768     0.772317
review_id                                768     0.772317
order_approved_at                        160     0.160899
payment_installments_total                 1     0.001006
payment_value_total                        1     0.001006
payment_type_count                         1     0.001006
customer_city                              0     0.000000
order_purchase_timestamp                   0     0.000000
order_status                               0     0.000000
customer_id                                0     0.000000
customer_state                             0     0.000000
customer_unique_id                         0     0.000000
customer_zip_code_prefix                   0     0.000000
order_estimated_delivery_date              0     0.000000
order_id                                   0     0.000000
late_delivery_flag                         0     0.000000
review_risk_flag                           0     0.000000

In [123]:
df["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [124]:
df["review_comment_title"]

0                     NaN
1        Muito boa a loja
2                     NaN
3                     NaN
4                     NaN
               ...
99436                 NaN
99437                 NaN
99438                 NaN
99439                 NaN
99440                 NaN
Name: review_comment_title, Length: 99441, dtype: str

In [125]:
df.iloc[1]

order_id                         53cdb2fc8bc7dce0b6741e2150273451
customer_id                      b0830fb4747a6c6d20dea0b8c802d7ef
order_status                                            delivered
order_purchase_timestamp                      2018-07-24 20:41:37
order_approved_at                             2018-07-26 03:24:27
order_delivered_carrier_date                  2018-07-26 14:31:00
order_delivered_customer_date                 2018-08-07 15:27:45
order_estimated_delivery_date                          2018-08-13
customer_unique_id               af07308b275d755c9edb36a90c618231
customer_zip_code_prefix                                    47813
customer_city                                           barreiras
customer_state                                                 BA
order_item_count                                              1.0
unique_sellers                                                1.0
unique_products                                               1.0
total_freight_value                                         22.76
total_item_value                                            118.7
payment_value_total                                        141.46
payment_installments_total                                    1.0
payment_type_count                                            1.0
review_id                        8d5266042046a06655c8db133d120ba5
review_score                                                  4.0
review_comment_title                             Muito boa a loja
review_comment_message                       Muito bom o produto.
review_creation_date                          2018-08-08 00:00:00
review_answer_timestamp                       2018-08-08 18:37:50
actual_delivery_days                                         13.0
delivery_delay_days                                          -6.0
late_delivery_flag                                          False
review_risk_flag                                            False
Name: 1, dtype: object

In [126]:
df.isna().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                  160
order_delivered_carrier_date      1783
order_delivered_customer_date     2965
order_estimated_delivery_date        0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
order_item_count                   775
unique_sellers                     775
unique_products                    775
total_freight_value                775
total_item_value                   775
payment_value_total                  1
payment_installments_total           1
payment_type_count                   1
review_id                          768
review_score                       768
review_comment_title             87889
review_comment_message           58665
review_creation_date               768
review_answer_timestamp            768
actual_delivery_days              2965
delivery_delay_days               2965
late_delivery_flag                   0
review_risk_flag                     0
dtype: int64

## Since Review score is unavailbale it would be better to drop it since replacing by mean or mode will not work

In [127]:
df = df.dropna(subset=['review_score'])

In [128]:
order_cols = [
    'order_id',
    'order_status',
    'total_item_value',
    'total_freight_value',
    'customer_state',
    'actual_delivery_days',
    'delivery_delay_days',
    'late_delivery_flag',
    'review_score',
    'review_risk_flag'
]

order_df=df[order_cols]

In [129]:
order_df

,order_id,order_status,total_item_value,total_freight_value,customer_state,actual_delivery_days,delivery_delay_days,late_delivery_flag,review_score,review_risk_flag
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,29.99,8.72,SP,8.0,-8.0,False,4.0,False
1,53cdb2fc8bc7dce0b6741e2150273451,delivered,118.70,22.76,BA,13.0,-6.0,False,4.0,False
2,47770eb9100c2d0c44946d9cf07ec65d,delivered,159.90,19.22,GO,9.0,-18.0,False,5.0,False
3,949d5b44dbf5de918fe9c16f97b45f8a,delivered,45.00,27.20,RN,13.0,-13.0,False,5.0,False
4,ad21c59c0840e6cb83a9ceb5573f8159,delivered,19.90,8.72,SP,2.0,-10.0,False,5.0,False
...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,delivered,72.00,13.08,SP,8.0,-11.0,False,5.0,False
99437,63943bddc261676b46f01ca7ac2f7bd8,delivered,174.90,20.10,SP,22.0,-2.0,False,4.0,False
99438,83c1379a015df1e13d02aae0204711ab,delivered,205.99,65.02,BA,24.0,-6.0,False,5.0,False
99439,11c177c8e97725db2631073c19f07b62,delivered,359.98,81.18,RJ,17.0,-21.0,False,2.0,True
99440,66dea50a8b16d9b4dee7af250b4be1a5,delivered,68.50,18.36,PR,7.0,-18.0,False,5.0,False

#### Understanding Columns 
- delivery_delay_columns: here if delivery_delay_columns is negative then product delivered early if 0 means then product delivered at exact time if positive then product delivered late
- total_freight_value: means total cost for shipping
- customer_state: state of Brazi where customer lives
- late_delievery_flag: True if product delivered late False otherwise
-  review_risk_flag: True if review is less than particular threshold of review_score otherwise false

In [130]:
order_df.info()

<class 'pandas.DataFrame'>
Index: 98673 entries, 0 to 99440
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              98673 non-null  str
 1   order_status          98673 non-null  str
 2   total_item_value      97917 non-null  float64
 3   total_freight_value   97917 non-null  float64
 4   customer_state        98673 non-null  str
 5   actual_delivery_days  95830 non-null  float64
 6   delivery_delay_days   95830 non-null  float64
 7   late_delivery_flag    98673 non-null  bool
 8   review_score          98673 non-null  float64
 9   review_risk_flag      98673 non-null  bool
dtypes: bool(2), float64(5), str(3)
memory usage: 7.0 MB

In [131]:
print("Shape of table: ",order_df.shape)
order_df.isna().sum()

Shape of table:  (98673, 10)

order_id                   0
order_status               0
total_item_value         756
total_freight_value      756
customer_state             0
actual_delivery_days    2843
delivery_delay_days     2843
late_delivery_flag         0
review_score               0
review_risk_flag           0
dtype: int64

- columns like actual_delivery_days and delivery_delay_days cannot be confidently replaced because the item was never reached to customer so better to drop them
-

In [132]:
order_df = order_df[
    order_df["actual_delivery_days"].notna()
].copy()

In [133]:
order_df.isna().sum()

order_id                0
order_status            0
total_item_value        0
total_freight_value     0
customer_state          0
actual_delivery_days    0
delivery_delay_days     0
late_delivery_flag      0
review_score            0
review_risk_flag        0
dtype: int64

Now our dataset is almost clean for columns: 'order_status', 'total_item_value', 'total_freight_value',
       'customer_state', 'actual_delivery_days', 'delivery_delay_days',
       'late_delivery_flag', 'review_score', 'review_risk_flag'

In [134]:
df.isna().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                  155
order_delivered_carrier_date      1746
order_delivered_customer_date     2843
order_estimated_delivery_date        0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
order_item_count                   756
unique_sellers                     756
unique_products                    756
total_freight_value                756
total_item_value                   756
payment_value_total                  1
payment_installments_total           1
payment_type_count                   1
review_id                            0
review_score                         0
review_comment_title             87121
review_comment_message           57897
review_creation_date                 0
review_answer_timestamp              0
actual_delivery_days              2843
delivery_delay_days               2843
late_delivery_flag                   0
review_risk_flag                     0
dtype: int64

In [138]:
new_df = df[df["order_id"].isin(order_df["order_id"])].copy()

In [139]:
new_df.shape

(95830, 30)

In [137]:
new_df.isna().sum()

order_id                             0
customer_id                          0
order_status                         0
order_purchase_timestamp             0
order_approved_at                   14
order_delivered_carrier_date         1
order_delivered_customer_date        0
order_estimated_delivery_date        0
customer_unique_id                   0
customer_zip_code_prefix             0
customer_city                        0
customer_state                       0
order_item_count                     0
unique_sellers                       0
unique_products                      0
total_freight_value                  0
total_item_value                     0
payment_value_total                  1
payment_installments_total           1
payment_type_count                   1
review_id                            0
review_score                         0
review_comment_title             84642
review_comment_message           56925
review_creation_date                 0
review_answer_timestamp              0
actual_delivery_days                 0
delivery_delay_days                  0
late_delivery_flag                   0
review_risk_flag                     0
dtype: int64

In [140]:
date_cols = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date",
    "review_creation_date",
    "review_answer_timestamp"
]

for col in date_cols:
    new_df[col] = pd.to_datetime(new_df[col], errors="coerce")

In [141]:
new_df["order_status"].value_counts()

order_status
delivered    95824
canceled         6
Name: count, dtype: int64

In [142]:
new_df["review_score"].value_counts().sort_index()

review_score
1.0     9356
2.0     2920
3.0     7918
4.0    18893
5.0    56743
Name: count, dtype: int64

In [143]:
new_df["late_delivery_flag"].value_counts()

late_delivery_flag
False    89448
True      6382
Name: count, dtype: int64

In [145]:
total_orders = new_df["order_id"].nunique()
avg_rating = new_df["review_score"].mean()
late_percentage = new_df["late_delivery_flag"].mean() * 100
avg_order_value = new_df["total_item_value"].mean()
avg_freight = new_df["total_freight_value"].mean()

In [146]:
print("Total Orders:", total_orders)
print("Average Rating:", avg_rating)
print("Late Delivery %:", late_percentage)
print("Average Order Value:", avg_order_value)
print("Average Freight:", avg_freight)

Total Orders: 95830
Average Rating: 4.155661066471877
Late Delivery %: 6.659709902953146
Average Order Value: 136.79839956172387
Average Freight: 22.762520505061044

In [150]:
new_df.to_csv("../data-visualization/cleaned_master_order_table.csv")